version: '2'

services:
  web:
    build: ./web
    restart: always
    ports:
     - "5000:5000"
    volumes:
     - ./web:/usr/src/app
    links:
      - db

  db:
    build: ./db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: experiments
